import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import {
  ArrowLeft,
  CheckCircle2,
  Circle,
  Clock,
  Route,
  Target,
} from "lucide-react";

import {
  getRoadmapByIdApi,
  toggleRoadmapDayApi,
} from "../api/roadmap.api";

import AppLayout from "../components/AppLayout";
import ErrorState from "../components/ErrorState";
import LoadingState from "../components/LoadingState";

const RoadmapDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [roadmap, setRoadmap] = useState(null);
  const [activeDay, setActiveDay] = useState(null);
  const [loading, setLoading] = useState(true);
  const [togglingDay, setTogglingDay] = useState(null);
  const [error, setError] = useState("");

  const fetchRoadmap = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await getRoadmapByIdApi(id);

      setRoadmap(response.data);
      setActiveDay(response.data.days?.[0] || null);
    } catch (error) {
      setError(error.response?.data?.message || "Failed to fetch roadmap");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRoadmap();
  }, [id]);

  const handleToggleDay = async (dayNumber) => {
    try {
      setTogglingDay(dayNumber);

      const response = await toggleRoadmapDayApi(id, dayNumber);

      setRoadmap(response.data);

      const updatedActiveDay = response.data.days?.find(
        (day) => day.day === dayNumber
      );

      if (updatedActiveDay) {
        setActiveDay(updatedActiveDay);
      }
    } catch (error) {
      alert(error.response?.data?.message || "Failed to update roadmap day");
    } finally {
      setTogglingDay(null);
    }
  };

  if (loading) {
    return (
      <AppLayout>
        <LoadingState
          title="Loading roadmap"
          message="Please wait while we fetch your AI-generated preparation roadmap."
        />
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <ErrorState
          title="Roadmap not found"
          message={error}
          buttonText="Back to Roadmaps"
          onRetry={() => navigate("/roadmaps")}
        />
      </AppLayout>
    );
  }

  if (!roadmap) return null;

  const completedDays = roadmap.completedDays?.length || 0;
  const totalDays = roadmap.durationInDays || roadmap.days?.length || 0;

  return (
    <AppLayout>
      <div className="mb-8">
        <Link
          to="/roadmaps"
          className="mb-5 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"
        >
          <ArrowLeft size={16} />
          Back to roadmap history
        </Link>

        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-blue-500/10 p-4 text-blue-300">
              <Route size={28} />
            </div>

            <div>
              <p className="font-medium text-blue-400">AI Roadmap</p>
              <h1 className="text-3xl font-bold">{roadmap.title}</h1>
            </div>
          </div>

          <p className="mt-4 text-slate-400">
            {roadmap.description ||
              "Personalized placement preparation roadmap generated by Hirenix AI."}
          </p>

          <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-4">
            <InfoBox label="Target Role" value={roadmap.targetRole} />
            <InfoBox label="Company" value={roadmap.targetCompany || "General"} />
            <InfoBox label="Duration" value={`${totalDays} days`} />
            <InfoBox label="Completed" value={`${completedDays}/${totalDays}`} />
          </div>

          <div className="mt-6">
            <div className="mb-2 flex justify-between text-sm">
              <span className="text-slate-400">Roadmap Progress</span>
              <span className="font-semibold text-slate-300">
                {roadmap.progressPercentage || 0}%
              </span>
            </div>

            <div className="h-3 overflow-hidden rounded-full bg-slate-800">
              <div
                className="h-full rounded-full bg-blue-600"
                style={{ width: `${roadmap.progressPercentage || 0}%` }}
              />
            </div>
          </div>
        </div>
      </div>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 xl:col-span-1">
          <h2 className="mb-5 text-xl font-semibold">Roadmap Days</h2>

          <div className="max-h-[650px] space-y-3 overflow-y-auto pr-2 [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-slate-950 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-gray-900">
            {roadmap.days?.map((day) => {
              const isCompleted = roadmap.completedDays?.includes(day.day);
              const isActive = activeDay?.day === day.day;

              return (
                <button
                  key={day.day}
                  onClick={() => setActiveDay(day)}
                  className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm transition ${
                    isActive
                      ? "border border-blue-500/40 bg-blue-500/10 text-blue-300"
                      : "bg-slate-950 text-slate-300 hover:bg-slate-800"
                  }`}
                >
                  <span>Day {day.day}</span>

                  {isCompleted ? (
                    <CheckCircle2 size={16} className="text-green-300" />
                  ) : (
                    <Circle size={16} className="text-slate-500" />
                  )}
                </button>
              );
            })}
          </div>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6 xl:col-span-2">
          {activeDay ? (
            <>
              <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                <div>
                  <p className="text-sm text-blue-400">Day {activeDay.day}</p>
                  <h2 className="mt-1 text-2xl font-semibold">
                    {activeDay.title}
                  </h2>
                  <p className="mt-3 text-sm leading-6 text-slate-400">
                    {activeDay.description}
                  </p>
                </div>

                <button
                  onClick={() => handleToggleDay(activeDay.day)}
                  disabled={togglingDay === activeDay.day}
                  className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold hover:bg-blue-700 disabled:opacity-70"
                >
                  {roadmap.completedDays?.includes(activeDay.day) ? (
                    <>
                      <CheckCircle2 size={18} />
                      {togglingDay === activeDay.day
                        ? "Updating..."
                        : "Mark Incomplete"}
                    </>
                  ) : (
                    <>
                      <Circle size={18} />
                      {togglingDay === activeDay.day
                        ? "Updating..."
                        : "Mark Complete"}
                    </>
                  )}
                </button>
              </div>

              <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
                <DetailCard
                  title="Tasks"
                  icon={Target}
                  items={activeDay.tasks}
                />

                <DetailCard
                  title="Resources"
                  icon={Route}
                  items={activeDay.resources}
                />

                <DetailCard
                  title="Practice"
                  icon={Clock}
                  items={activeDay.practice}
                />

                <DetailCard
                  title="Outcome"
                  icon={CheckCircle2}
                  items={activeDay.outcome ? [activeDay.outcome] : []}
                />
              </div>
            </>
          ) : (
            <div className="rounded-xl bg-slate-950 p-8 text-center text-slate-400">
              Select a roadmap day to view details.
            </div>
          )}
        </div>
      </section>
    </AppLayout>
  );
};

const InfoBox = ({ label, value }) => {
  return (
    <div className="rounded-xl bg-slate-950 p-4">
      <p className="text-xs text-slate-500">{label}</p>
      <p className="mt-1 font-semibold capitalize">{String(value || "N/A")}</p>
    </div>
  );
};

const DetailCard = ({ title, icon: Icon, items = [] }) => {
  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-950 p-5">
      <div className="mb-4 flex items-center gap-3">
        <div className="rounded-xl bg-blue-500/10 p-3 text-blue-300">
          <Icon size={20} />
        </div>

        <h3 className="text-lg font-semibold">{title}</h3>
      </div>

      {items?.length > 0 ? (
        <ul className="space-y-3">
          {items.map((item, index) => (
            <li
              key={index}
              className="rounded-xl bg-slate-900 px-4 py-3 text-sm leading-6 text-slate-300"
            >
              {item}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-slate-400">No data available.</p>
      )}
    </div>
  );
};

export default RoadmapDetails;