import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import {
  CheckCircle2,
  Circle,
  Clock,
  Route,
  Target,
} from "lucide-react";

import {
  getRoadmapByIdApi,
  toggleRoadmapDayApi,
} from "../api/roadmap.api";

import AppLayout from "../components/AppLayout";
import ErrorState from "../components/ErrorState";
import LoadingState from "../components/LoadingState";
import PageHeader from "../components/PageHeader";
import SectionCard from "../components/SectionCard";

const RoadmapDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [roadmap, setRoadmap] = useState(null);
  const [activeDay, setActiveDay] = useState(null);
  const [loading, setLoading] = useState(true);
  const [togglingDay, setTogglingDay] = useState(null);
  const [error, setError] = useState("");

  const normalizeRoadmapDays = (roadmapData) => {
    const possibleDays =
      roadmapData?.days ||
      roadmapData?.roadmapDays ||
      roadmapData?.dailyPlan ||
      roadmapData?.plan ||
      roadmapData?.schedule ||
      [];

    if (!Array.isArray(possibleDays)) return [];

    return possibleDays.map((item, index) => ({
      _id: item._id || item.id || index + 1,
      day: item.day || item.dayNumber || item.dayNo || index + 1,
      title:
        item.title ||
        item.topic ||
        item.focus ||
        item.heading ||
        `Day ${index + 1}`,
      description:
        item.description ||
        item.summary ||
        item.goal ||
        item.objective ||
        "Complete the planned preparation tasks for this day.",
      tasks: item.tasks || item.taskList || item.activities || [],
      resources: item.resources || item.learningResources || item.links || [],
      practice: item.practice || item.practiceProblems || item.exercises || [],
      outcome: item.outcome || item.expectedOutcome || item.result || "",
    }));
  };

  const fetchRoadmap = async () => {
    try {
      setLoading(true);
      setError("");

      const response = await getRoadmapByIdApi(id);
      const roadmapData = response.data;

      const normalizedDays = normalizeRoadmapDays(roadmapData);

      const finalRoadmap = {
        ...roadmapData,
        days: normalizedDays,
      };

      setRoadmap(finalRoadmap);
      setActiveDay(normalizedDays[0] || null);

      console.log("Roadmap details response:", roadmapData);
      console.log("Normalized roadmap days:", normalizedDays);
    } catch (error) {
      setError(error.response?.data?.message || "Failed to fetch roadmap");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRoadmap();
  }, [id]);

  const completedDayNumbers = useMemo(() => {
    if (!roadmap?.completedDays) return [];

    return roadmap.completedDays.map((item) => {
      if (typeof item === "object") {
        return item.day || item.dayNumber || item.dayNo;
      }

      return item;
    });
  }, [roadmap]);

  const isDayCompleted = (dayNumber) => {
    return completedDayNumbers.includes(dayNumber);
  };

  const handleToggleDay = async (dayNumber) => {
    try {
      setTogglingDay(dayNumber);

      const response = await toggleRoadmapDayApi(id, dayNumber);
      const roadmapData = response.data;

      const normalizedDays = normalizeRoadmapDays(roadmapData);

      const finalRoadmap = {
        ...roadmapData,
        days: normalizedDays,
      };

      setRoadmap(finalRoadmap);

      const updatedActiveDay = normalizedDays.find(
        (day) => Number(day.day) === Number(dayNumber)
      );

      if (updatedActiveDay) {
        setActiveDay(updatedActiveDay);
      }
    } catch (error) {
      alert(error.response?.data?.message || "Failed to update roadmap day");
    } finally {
      setTogglingDay(null);
    }
  };

  if (loading) {
    return (
      <AppLayout>
        <LoadingState
          title="Loading roadmap"
          message="Please wait while we fetch your AI-generated preparation roadmap."
        />
      </AppLayout>
    );
  }

  if (error) {
    return (
      <AppLayout>
        <ErrorState
          title="Roadmap not found"
          message={error}
          buttonText="Back to Roadmaps"
          onRetry={() => navigate("/roadmaps")}
        />
      </AppLayout>
    );
  }

  if (!roadmap) return null;

  const completedDays = completedDayNumbers.length;
  const totalDays =
    roadmap.durationInDays || roadmap.days?.length || roadmap.totalDays || 0;

  return (
    <AppLayout>
      <PageHeader
        eyebrow="AI Roadmap"
        title={roadmap.title || "Placement Roadmap"}
        description={
          roadmap.description ||
          "Personalized placement preparation roadmap generated by Hirenix AI."
        }
        icon={Route}
        backPath="/roadmaps"
        backLabel="Back to roadmap history"
      />

      <SectionCard className="mb-8">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-4">
          <InfoBox label="Target Role" value={roadmap.targetRole} />
          <InfoBox label="Company" value={roadmap.targetCompany || "General"} />
          <InfoBox label="Duration" value={`${totalDays} Days`} />
          <InfoBox label="Completed" value={`${completedDays}/${totalDays}`} />
        </div>

        <div className="mt-6">
          <div className="mb-2 flex justify-between text-sm">
            <span className="text-slate-400">Roadmap Progress</span>
            <span className="font-semibold text-slate-300">
              {roadmap.progressPercentage || 0}%
            </span>
          </div>

          <div className="h-3 overflow-hidden rounded-full bg-slate-800">
            <div
              className="h-full rounded-full bg-blue-600"
              style={{ width: `${roadmap.progressPercentage || 0}%` }}
            />
          </div>
        </div>
      </SectionCard>

      <section className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <SectionCard
          title="Roadmap Days"
          description="Select a day to view tasks, resources, practice, and outcome."
          icon={Route}
        >
          {roadmap.days?.length > 0 ? (
            <div className="max-h-[650px] space-y-3 overflow-y-auto pr-2 [&::-webkit-scrollbar]:w-2 [&::-webkit-scrollbar-track]:bg-slate-950 [&::-webkit-scrollbar-thumb]:rounded-full [&::-webkit-scrollbar-thumb]:bg-gray-900">
              {roadmap.days.map((day) => {
                const completed = isDayCompleted(day.day);
                const active = Number(activeDay?.day) === Number(day.day);

                return (
                  <button
                    key={day._id || day.day}
                    onClick={() => setActiveDay(day)}
                    className={`flex w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm transition ${
                      active
                        ? "border border-blue-500/40 bg-blue-500/10 text-blue-300"
                        : "bg-slate-950 text-slate-300 hover:bg-slate-800"
                    }`}
                  >
                    <div>
                      <p className="font-semibold">Day {day.day}</p>
                      <p className="mt-1 line-clamp-1 text-xs text-slate-500">
                        {day.title}
                      </p>
                    </div>

                    {completed ? (
                      <CheckCircle2 size={16} className="text-green-300" />
                    ) : (
                      <Circle size={16} className="text-slate-500" />
                    )}
                  </button>
                );
              })}
            </div>
          ) : (
            <div className="rounded-xl bg-slate-950 p-8 text-center text-slate-400">
              No roadmap days found in this roadmap. Check backend response field
              name for days.
            </div>
          )}
        </SectionCard>

        <SectionCard
          title={activeDay ? `Day ${activeDay.day}` : "Day Details"}
          description={
            activeDay
              ? "Complete the tasks and mark this day as completed."
              : "Select a roadmap day to view details."
          }
          icon={Target}
          className="xl:col-span-2"
        >
          {activeDay ? (
            <>
              <div className="mb-6 flex flex-col gap-4 md:flex-row md:items-start md:justify-between">
                <div>
                  <h2 className="text-2xl font-semibold">{activeDay.title}</h2>
                  <p className="mt-3 text-sm leading-6 text-slate-400">
                    {activeDay.description}
                  </p>
                </div>

                <button
                  onClick={() => handleToggleDay(activeDay.day)}
                  disabled={togglingDay === activeDay.day}
                  className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold hover:bg-blue-700 disabled:opacity-70"
                >
                  {isDayCompleted(activeDay.day) ? (
                    <>
                      <CheckCircle2 size={18} />
                      {togglingDay === activeDay.day
                        ? "Updating..."
                        : "Mark Incomplete"}
                    </>
                  ) : (
                    <>
                      <Circle size={18} />
                      {togglingDay === activeDay.day
                        ? "Updating..."
                        : "Mark Complete"}
                    </>
                  )}
                </button>
              </div>

              <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
                <DetailCard
                  title="Tasks"
                  icon={Target}
                  items={activeDay.tasks}
                />

                <DetailCard
                  title="Resources"
                  icon={Route}
                  items={activeDay.resources}
                />

                <DetailCard
                  title="Practice"
                  icon={Clock}
                  items={activeDay.practice}
                />

                <DetailCard
                  title="Outcome"
                  icon={CheckCircle2}
                  items={activeDay.outcome ? [activeDay.outcome] : []}
                />
              </div>
            </>
          ) : (
            <div className="rounded-xl bg-slate-950 p-8 text-center text-slate-400">
              Select a roadmap day to view details.
            </div>
          )}
        </SectionCard>
      </section>
    </AppLayout>
  );
};

const InfoBox = ({ label, value }) => {
  return (
    <div className="rounded-xl bg-slate-950 p-4">
      <p className="text-xs text-slate-500">{label}</p>
      <p className="mt-1 font-semibold capitalize">{String(value || "N/A")}</p>
    </div>
  );
};

const DetailCard = ({ title, icon: Icon, items = [] }) => {
  const normalizedItems = Array.isArray(items) ? items : [items].filter(Boolean);

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-950 p-5">
      <div className="mb-4 flex items-center gap-3">
        <div className="rounded-xl bg-blue-500/10 p-3 text-blue-300">
          <Icon size={20} />
        </div>

        <h3 className="text-lg font-semibold">{title}</h3>
      </div>

      {normalizedItems.length > 0 ? (
        <ul className="space-y-3">
          {normalizedItems.map((item, index) => (
            <li
              key={index}
              className="rounded-xl bg-slate-900 px-4 py-3 text-sm leading-6 text-slate-300"
            >
              {typeof item === "object"
                ? item.title || item.name || item.description || JSON.stringify(item)
                : item}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-slate-400">No data available.</p>
      )}
    </div>
  );
};

export default RoadmapDetails;